# SKIP(Social Knowledge & Innovation Platform)
# Copyright (C) 2008-2010 TIS Inc.
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#  This program is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#  GNU General Public License for more details.
#
#  You should have received a copy of the GNU General Public License
#  along with this program.  If not, see <http://www.gnu.org/licenses/>.

# ==================================================================================================
# 全体設定
# ==================================================================================================

# 名称 名前
# --------------------------------------------------------------------------------------------------
abbr_app_title:
  default: SKIP                                            # システムの名称
login_account:
  default: ログインID                                      # ログインアカウントの名称
point_button:
  default: GoodJob                                         # 記事へのポイント評価の名称（へぇ～などに変更できます）

# お問い合わせ
# --------------------------------------------------------------------------------------------------
contact_addr:
  format: email
  default: admin@example.com

# フッター
# --------------------------------------------------------------------------------------------------
footer_first:                                              # フッターの１行目（ヘルプ・規約へのリンクなどを推奨）
  default: >-
    <b><a onclick="open_site(); return false;" href="#">このサイトについて</a> - <a onclick="open_rule(); return false;" href="#">利用規約</a></b>
footer_second:
  default: お問い合わせはこちら | Since 2008 SKIP          # フッターの２列目（提供元への連絡先などを推奨）
footer_image_link_url:
  format: url
  default: http://www.openskip.org/                        # フッター右側に表示する画像のリンクURL

# メール
# --------------------------------------------------------------------------------------------------
contact_mail_contain_contents:
  format: boolean
  default: false

# ブログへの埋め込みタグ
# --------------------------------------------------------------------------------------------------
youtube:
  format: boolean
  default: false
slideshare:
  format: boolean
  default: false
googlemap:
  format: boolean
  default: false

# その他
# --------------------------------------------------------------------------------------------------
stop_new_user:
  format: boolean
  default: false
hide_email:
  format: boolean
  default: false
activation_lifetime:                                       # サインアップURLの有効期間(単位:日)
  format: int
  default: 5
enable_change_picture:
  format: boolean
  default: true
enable_change_section:
  format: boolean
  default: true
access_record_limit:
  format: int
  default: 30
entry_showed_tab_limit_per_page:
  format: int
  default: 20
close_question_limit:
  format: int
  default: 30

# ==================================================================================================
# RSSフィードの設定
# ==================================================================================================
mypage_feed_default_limit:         # マイページで表示するRSSフィードの設定(デフォルトの1フィードあたりの最大表示件数)
  format: int
  default: 3
mypage_feed_timeout:               # マイページで表示するRSSフィードのタイムアウト(秒)
  format: int
  default: 7

# RSSフィードの詳細設定
# :url:   フィードのURL
# :title: フィードのタイトル(フィード内のタイトル以外のものを設定したい場合)
# :limit: フィードの最大表示件数
mypage_feed_settings:
  serialized: true
  default: [{ :url: http://news.skipaas.jp/rss.xml, :title: SKIPニュース, :limit: 5 }]

# ==================================================================================================
# セキュリティ設定
# ==================================================================================================
enable_user_lock:
  format: boolean
  default: true
user_lock_trial_limit:
  format: int
  default: 3
enable_password_periodic_change:
  format: boolean
  default: true
password_change_interval:
  format: int
  default: 180
password_strength:
  default: middle
custom_password_strength_regex:
  default:
  format: regex
custom_password_strength_validation_message:
  default:
enable_login_keyphrase:
  format: boolean
  default: false
login_keyphrase:
  default: skip
enable_user_cleaning_notification:
  format: boolean
  default: false
user_cleaning_notification_interval:
  format: int
  default: 3
enable_single_session:
  format: boolean
  default: true

# ==================================================================================================
# 画面なし
# ==================================================================================================
default_send_mail_of_question:                            # 質問記事のメール送信チェックボックスのデフォルト値[画面なし]
  format: boolean
  default: true

enable_send_email_to_all_users:                           # 全体へのメール送信機能を有効にするかどうか[画面なし]
  format: boolean
  defalut: true

acceptable_hosts_to_provide_openid_account:               # OpenID認証でプロバイダーとしてIDを発行するホストのホワイトリスト
  serialized: true
  default: ["http://localhost:3333/consumer"]

enable_invitation_feature:                                # 招待機能の有効化
  format: boolean
  default: false

simple_apps:                                              # オープンソース版では利用できません
  serialized: true
  default:
    url: "http://localhost:4000/"
    event:
      enable: true

default_theme:                                            # 既定のテーマ
  default: silver

hide_header_logout_link:                                  # ヘッダのログアウトリンクの表示/非表示切り替え
  format: boolean
  default: false

footer_image_link_tag:
  default: ""

max_total_file_size_per_tenant:                           # テナント毎のファイルサイズ最大値
  format: int
  default: 1073741824
